# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/verilog/lab4/lab4/lab4.cache/wt [current_project]
set_property parent.project_path C:/verilog/lab4/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/imports/lab4/lab4_1_compare.v
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/imports/lab4/lab4_1_memory.v
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/imports/lab4/lab4_1_add.v
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/imports/lab4/lab4_1_register.v
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/imports/lab4/lab4_1_mulchoose.v
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/new/FSM.v
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/imports/lab4/lab4_1.v
  C:/verilog/lab4/lab4/lab4.srcs/sources_1/new/autooperate.v
}
read_xdc {{C:/verilog/lab4/lab4/lab4.srcs/constrs_1/imports/实验2 -  简单组合电路设计_v3_2/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/verilog/lab4/lab4/lab4.srcs/constrs_1/imports/实验2 -  简单组合电路设计_v3_2/Nexys4DDR_Master.xdc}}]

synth_design -top autooperate -part xc7a100tcsg324-1
write_checkpoint -noxdef autooperate.dcp
catch { report_utilization -file autooperate_utilization_synth.rpt -pb autooperate_utilization_synth.pb }
